### ISSUE TITLE
Not a issues Skins url

### ISSUE THREAD

**Issue by Tokoagar** [XSProject/XtremeServer#2]
I got two skin url alien and (itsalreadythere) here they are:

alien :https://configs-web.agario.miniclippt.com/live/v4/112/Grey.png

put it in customskin.txt

**Comment by Tokoagar** [comment]
.Close

**Comment by XtremePlayzCODE** [comment]
It's already there, maybe I will find the current skins and rename them to the in game names

**Comment by Tokoagar** [comment]
ok I find goblin skin <witch>

**Comment by Tokoagar** [comment]
<witch>

**Comment by Tokoagar** [comment]
write witch in bracket

**Comment by XtremePlayzCODE** [comment]
?
